default: &default
  adapter: postgresql
  encoding: unicode
  user: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: gonner_development

test:
  <<: *default
  database: gonner_test
